version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn finace_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envdb
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:80
    depends_on:
      - web
  redis:
    image: redis:6.2.6-alpine
    command: redis-server
    ports:
      - "14000:6379"
  react-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /frontend
      - /frontend/node_modules
    ports:
      - '1340:80'




volumes:
  postgres_data:
  static_volume:
  media_volume: