version: '3.8'

services:

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:80
    depends_on:
      - web

  react-prod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /frontend
      - /frontend/node_modules
    ports:
      - '1340:80'




volumes:
  static_volume:
  media_volume: