# Generated by Django 3.2 on 2021-07-05 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0014_auto_20210525_0737'),
        ('strategies', '0002_auto_20210617_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyticker',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_tickers', to='strategies.strategy'),
        ),
        migrations.AlterField(
            model_name='strategyticker',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickers.ticker'),
        ),
    ]
