# Generated by Django 3.0.5 on 2021-04-11 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('variance', models.DecimalField(decimal_places=150, default=0, max_digits=200)),
                ('starting_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('maximum_cash', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=200)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('market_variance', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('camp', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickers.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('starting_value_of_ticker', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value_of_ticker', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickers', to='tickers.Portfolio')),
                ('ticker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickers.Ticker')),
            ],
        ),
    ]
