# Generated by Django 3.0.5 on 2021-04-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='value',
        ),
        migrations.AddField(
            model_name='ticker',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='camp',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='coverage',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market_variance',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
