# Generated by Django 3.0.5 on 2021-04-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0002_auto_20210411_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='simply_return',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Simply Rate of Return', max_digits=30),
        ),
    ]
