# Generated by Django 3.0.5 on 2021-04-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0003_ticker_simply_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='annual_returns',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ticker',
            name='log_return',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Log Return', max_digits=30),
        ),
    ]
