# Generated by Django 3.0.5 on 2021-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0004_auto_20210412_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='standard_deviation',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=30),
        ),
    ]
