# Generated by Django 3.0.5 on 2021-04-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0005_ticker_standard_deviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='expected_portfolio_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='expected_portfolio_volatility',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userticker',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
