# Generated by Django 3.0.5 on 2021-04-18 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0006_auto_20210417_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userticker',
            name='is_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userticker',
            name='is_sell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userticker',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='HistoricTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('coverage', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('market_variance', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('camp', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=30, null=True)),
                ('simply_return', models.DecimalField(decimal_places=4, default=0, help_text='Simply Rate of Return', max_digits=30)),
                ('log_return', models.DecimalField(decimal_places=4, default=0, help_text='Log Return', max_digits=30)),
                ('standard_deviation', models.DecimalField(decimal_places=4, default=0, max_digits=30)),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historic_ticker', to='tickers.UserTicker')),
            ],
        ),
    ]
