# Generated by Django 3.0.5 on 2021-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0009_auto_20210425_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticker',
            name='date_buy',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userticker',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
