# Generated by Django 3.2 on 2021-04-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0010_auto_20210425_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
