# Generated by Django 3.2 on 2021-04-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0012_portfolio_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='expected_portfolio_variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
