# Generated by Django 3.2 on 2021-05-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0013_portfolio_expected_portfolio_variance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicticker',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicticker',
            name='camp',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicticker',
            name='coverage',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicticker',
            name='log_return',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Log Return', max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicticker',
            name='market_variance',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicticker',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicticker',
            name='simply_return',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Simply Rate of Return', max_digits=30),
        ),
        migrations.AlterField(
            model_name='historicticker',
            name='standard_deviation',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='expected_portfolio_return',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='expected_portfolio_variance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='expected_portfolio_volatility',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='maximum_cash',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='camp',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='coverage',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='log_return',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Log Return', max_digits=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market_variance',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='sharp',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='simply_return',
            field=models.DecimalField(decimal_places=8, default=0, help_text='Simply Rate of Return', max_digits=30),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='standard_deviation',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userticker',
            name='current_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userticker',
            name='current_value_of_ticker',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userticker',
            name='starting_investment',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userticker',
            name='starting_value_of_ticker',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='userticker',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
