# Generated by Django 3.1.6 on 2021-08-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0014_auto_20210525_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
