# Generated by Django 3.2 on 2021-05-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdaterange',
            name='end',
            field=models.DateField(blank=True),
        ),
    ]
