export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CURRENT_USER = 'CURRENT_USER';


export const FETCH_TICKERS = 'FETCH_TICKERS';
export const FETCH_TICKER = 'FETCH_TICKER';
export const UPDATE_TICKER = 'UPDATE_TICKER';
export const FETCH_GROUP = 'FETCH_GROUP';


export const FETCH_PORTFOLIOS = 'PORTFOLIOS_REQUEST';
export const FETCH_USER_PORTFOLIOS = 'USER_PORTFOLIOS';
export const FETCH_USER_SELECTED_PORTFOLIO = 'FETCH_USER_SELECTED_PORTFOLIO';
export const CLEAR_USER_SELECTED_PORTFOLIO = 'CLEAR_USER_SELECTED_PORTFOLIO';
export const FETCH_PORTFOLIO_SELECTED_ITEMS = 'FETCH_PORTFOLIO_SELECTED_ITEMS';

export const FETCH_TOTAL_USER_DATA = 'FETCH_TOTAL_USER_DATA';